version: "3"
services:
  web:
    build: ./app
    ports:
      - "8127:5000"
    environment:
      FLASK_APP: app.py
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    build: ./db
    ports:
      - "8269:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
networks:
  backend:
    driver: bridge